schema = 3

[mod]
  [mod."dario.cat/mergo"]
    version = "v1.0.1"
    hash = "sha256-wcG6+x0k6KzOSlaPA+1RFxa06/RIAePJTAjjuhLbImw="
  [mod."github.com/99designs/go-keychain"]
    version = "v0.0.0-20191008050251-8e49817e8af4"
    hash = "sha256-4EndKcspGC3GOPCmctXF1NnWzxWwMyY/OQpFMmr8Sc0="
  [mod."github.com/99designs/keyring"]
    version = "v1.2.2"
    hash = "sha256-9wMtqgdji5I+vdyD4cf3XTfMEoUn49UG1z84IE0V7E0="
  [mod."github.com/MakeNowJust/heredoc"]
    version = "v1.0.0"
    hash = "sha256-8hKERAVV1Pew84kc9GkW23dcO8uIUx/+tJQLi+oPwqE="
  [mod."github.com/Masterminds/goutils"]
    version = "v1.1.1"
    hash = "sha256-MEvA5e099GUllILa5EXxa6toQexU1sz6eDZt2tiqpCY="
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.3.0"
    hash = "sha256-fBG3nuxEW+0fRHegSzj7q4GyEMCINeOUbkfqFG2cU+8="
  [mod."github.com/Masterminds/sprig/v3"]
    version = "v3.3.0"
    hash = "sha256-NvFX1xRO5t/u8OI063SDPfqYcZ43AuLI6klA6daPV9I="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.4.14"
    hash = "sha256-o3bmSJnZc20Xhybk/oPj9+LqJAVDnvTZ+ELPRFPkZFg="
  [mod."github.com/alecthomas/kong"]
    version = "v1.2.1"
    hash = "sha256-khU0G4vpNuzSdw0FnOTWeCCGu1FWn7ZNn0kFrWBPQJ8="
  [mod."github.com/atotto/clipboard"]
    version = "v0.1.4"
    hash = "sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk="
  [mod."github.com/aws/aws-sdk-go-v2"]
    version = "v1.30.5"
    hash = "sha256-h34zXa7o3Y9Tsya45FSAAO+22t7uR3QKLUyoclAaZdo="
  [mod."github.com/aws/aws-sdk-go-v2/config"]
    version = "v1.27.24"
    hash = "sha256-6TGRSmNo3bD6GURvRTFDVwpMNOoVXleMqSW+oOpKGaY="
  [mod."github.com/aws/aws-sdk-go-v2/credentials"]
    version = "v1.17.24"
    hash = "sha256-NrY1D+flIx8uB1pCKanTPFGQu2UdBiJhwI1l8wEUbus="
  [mod."github.com/aws/aws-sdk-go-v2/feature/ec2/imds"]
    version = "v1.16.9"
    hash = "sha256-ZS1eVLQSjTGtB6tC5+wvfXmxw7QmHOAA3Qx8CZ05/n0="
  [mod."github.com/aws/aws-sdk-go-v2/internal/configsources"]
    version = "v1.3.13"
    hash = "sha256-HV7jKTjq73itxJ6+UHp+RIqQLPhyjrfLSJwLJeFjXG8="
  [mod."github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"]
    version = "v2.6.13"
    hash = "sha256-Gua+ntvLRZqqMyb/dqZBcwPQTp00JtIYdkQPVZQcLWc="
  [mod."github.com/aws/aws-sdk-go-v2/internal/ini"]
    version = "v1.8.0"
    hash = "sha256-v76jTAr4rEgS5en49ikLh6nuvclN+VjpOPj83ZQ3sLo="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding"]
    version = "v1.11.3"
    hash = "sha256-TRhoRd7iY7K+pfdkSQLItyr52k2jO4TMYQ5vRGiOOMk="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"]
    version = "v1.11.15"
    hash = "sha256-3LXZuXkWqfLbMB4aQCXjuQdup95ncfZVJBvtujplLDM="
  [mod."github.com/aws/aws-sdk-go-v2/service/sso"]
    version = "v1.22.1"
    hash = "sha256-anUdhNNO1JlENH9tMteaQhh+O1EvlbXdW2PtXn74qrY="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssooidc"]
    version = "v1.26.2"
    hash = "sha256-L7fEUHMnm4JtFhJOuYd2x7RFOrO0zlGqEZeGDbuSLrA="
  [mod."github.com/aws/aws-sdk-go-v2/service/sts"]
    version = "v1.30.1"
    hash = "sha256-90Yx5Gvi/z3ZMA9SBJ+RhSNkBJsurN6ori9f/S8JrXQ="
  [mod."github.com/aws/smithy-go"]
    version = "v1.20.4"
    hash = "sha256-lli4lJ5s3i3T97SLFjlUDDR0SDOYTRbvOq3nHKPQk7U="
  [mod."github.com/c-bata/go-prompt"]
    version = "v0.2.5"
    hash = "sha256-1ZgTsFgpcHmGxIqBy7oGhqjj+pgUhjVjBIBNeb1+55g="
  [mod."github.com/chzyer/readline"]
    version = "v0.0.0-20180603132655-2972be24d48e"
    hash = "sha256-2Uj5LGpHEbLQG3d/7z9AL8DknUBZyoTAMs4j+VVDmIA="
  [mod."github.com/containerd/log"]
    version = "v0.1.0"
    hash = "sha256-vuE6Mie2gSxiN3jTKTZovjcbdBd1YEExb7IBe3GM+9s="
  [mod."github.com/danieljoos/wincred"]
    version = "v1.1.2"
    hash = "sha256-Nnklfg12vmWCOhELGyoRqEF4w4srp0WbPwreaChYLKs="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/distribution/reference"]
    version = "v0.6.0"
    hash = "sha256-gr4tL+qz4jKyAtl8LINcxMSanztdt+pybj1T+2ulQv4="
  [mod."github.com/docker/docker"]
    version = "v27.2.1+incompatible"
    hash = "sha256-iHbWQ7NJRh0qfu5Bi1K9HdZUzGq3UI9B12yZyZC1XKM="
  [mod."github.com/docker/go-connections"]
    version = "v0.5.0"
    hash = "sha256-aGbMRrguh98DupIHgcpLkVUZpwycx1noQXbtTl5Sbms="
  [mod."github.com/docker/go-units"]
    version = "v0.5.0"
    hash = "sha256-iK/V/jJc+borzqMeqLY+38Qcts2KhywpsTk95++hImE="
  [mod."github.com/dvsekhvalnov/jose2go"]
    version = "v1.6.0"
    hash = "sha256-IXn2BuUp4fi/i2zf1tGGW1m9xoYh3VCksB6GJ5Sf06g="
  [mod."github.com/fatih/color"]
    version = "v1.17.0"
    hash = "sha256-QsKMy3MsvjbYNcA9jP8w6c3wpmWDZ0079bybAEzmXR0="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.4.9"
    hash = "sha256-HZBMhbFqcZM9oxSbWqISzEE7GF7JZpco5tyta6c4OcQ="
  [mod."github.com/go-json-experiment/json"]
    version = "v0.0.0-20240815174924-0599f16bf0e2"
    hash = "sha256-syPFqrgN5Gr5aZNaFdB/NliYmBcxlYmlZAYDexD8w+g="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.2"
    hash = "sha256-/W6qGilFlZNTb9Uq48xGZ4IbsVeSwJiAMLw4wiNYHLI="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/goccy/go-yaml"]
    version = "v1.12.0"
    hash = "sha256-0mCOEhUeOmQOU66adWwh+53SUSowpVrm8ILwLhVGc6g="
  [mod."github.com/godbus/dbus"]
    version = "v0.0.0-20190726142602-4481cbc300e2"
    hash = "sha256-R7Gb9+Zjy80FbQSDGketoVEqfdOQKuOVTfWRjQ5kxZY="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gsterjov/go-libsecret"]
    version = "v0.0.0-20161001094733-a6f4afe4910c"
    hash = "sha256-Z5upjItPU9onq5t7VzhdQFp13lMJrSiE3gNRapuK6ic="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.0.0"
    hash = "sha256-LGSLrefkABG1kH1i+GUWiD2/ggJxiZEJ+D2YNbhZjmo="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.0"
    hash = "sha256-c0zgZsrOoA1+j7N7uIU0ZAUAa7mM8t9nfJgele+/sl4="
  [mod."github.com/hexops/gotextdiff"]
    version = "v1.0.3"
    hash = "sha256-wVs5uJs2KHU1HnDCDdSe0vIgNZylvs8oNidDxwA3+O0="
  [mod."github.com/huandu/xstrings"]
    version = "v1.5.0"
    hash = "sha256-q4F/rzbWMDmOVv07RVApdpfIsRNRByfOUQPEKsTq5BM="
  [mod."github.com/knadh/koanf"]
    version = "v1.5.0"
    hash = "sha256-7Z4S5kFjVaroZh9yIqQamsEmKKVC3KQfkwjyPx1O/00="
  [mod."github.com/lmittmann/tint"]
    version = "v1.0.5"
    hash = "sha256-NthPT7c1Q2VSp5IrWMGAvzX7AxEcTKk+O0F56pgaTsQ="
  [mod."github.com/manifoldco/promptui"]
    version = "v0.9.0"
    hash = "sha256-Fe2OPoyRExZejwtUBivKhfJAJW7o9b1eyYpgDlWQ1No="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.9"
    hash = "sha256-dK/kIPe1tcxEubwI4CWfov/HWRBgD/fqlPC3d5i30CY="
  [mod."github.com/mattn/go-tty"]
    version = "v0.0.3"
    hash = "sha256-bo/iZY5yai2VvmeIt5M5ItI8l/SEL6RemYVdAfAwLTQ="
  [mod."github.com/mitchellh/copystructure"]
    version = "v1.2.0"
    hash = "sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/mitchellh/reflectwalk"]
    version = "v1.0.2"
    hash = "sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s="
  [mod."github.com/moby/docker-image-spec"]
    version = "v1.3.1"
    hash = "sha256-xwSNLmMagzywdGJIuhrWl1r7cIWBYCOMNYbuDDT6Jhs="
  [mod."github.com/moby/term"]
    version = "v0.5.0"
    hash = "sha256-jy0kbkeUsr0KoiE33WLxNAgYXZIERKR2O5+saXBwdD8="
  [mod."github.com/morikuni/aec"]
    version = "v1.0.0"
    hash = "sha256-5zYgLeGr3K+uhGKlN3xv0PO67V+2Zw+cezjzNCmAWOE="
  [mod."github.com/mtibben/percent"]
    version = "v0.2.1"
    hash = "sha256-Zj1lpCP6mKQ0UUTMs2By4LC414ou+iJzKkK+eBHfEcc="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.1.0"
    hash = "sha256-5OxW1ShHypLpzVu+BJivNlFX2JFPh9WKfJcMIgPZf4U="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pkg/term"]
    version = "v1.1.0"
    hash = "sha256-4zgH0pWzCb8f/98ACk+GPF1D5iFBjzr+Ybjsb4qQnjo="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/posener/complete"]
    version = "v1.2.3"
    hash = "sha256-/17KFHD0SsGALg9iLXNIdvVFcotOO+H6bOOD5SY0MVs="
  [mod."github.com/riywo/loginshell"]
    version = "v0.0.0-20200815045211-7d26008be1ab"
    hash = "sha256-keDEue4jkpIVm9GxZYAAIvYlDjk/eilAT/xGanTcHo0="
  [mod."github.com/shopspring/decimal"]
    version = "v1.4.0"
    hash = "sha256-U36bC271jQsjuWFF8BfLz4WicxPJUcPHRGxLvTz4Mdw="
  [mod."github.com/skratchdot/open-golang"]
    version = "v0.0.0-20200116055534-eef842397966"
    hash = "sha256-XUA03mdcSkQvAVQz9NBbikZWe75tukH2tNJQGaUCyso="
  [mod."github.com/spf13/cast"]
    version = "v1.7.0"
    hash = "sha256-xO2kSmNmMHaJ1i3T0ou0pcaBCusuO6Ep3xtF1P7ZadA="
  [mod."github.com/stretchr/testify"]
    version = "v1.9.0"
    hash = "sha256-uUp/On+1nK+lARkTVtb5RxlW15zxtw2kaAFuIASA+J0="
  [mod."github.com/synfinatic/flexlog"]
    version = "v0.0.5"
    hash = "sha256-23zivLTNRJF63FRTDASBGwjW7ETjc1MH8XlAa4qRrlU="
  [mod."github.com/synfinatic/gotable"]
    version = "v0.0.3"
    hash = "sha256-YQfVnVQUSiNDskRckUIT5ySu20kwy47tKHNEi+jELxM="
  [mod."github.com/veqryn/slog-json"]
    version = "v0.3.0"
    hash = "sha256-mOA0JKK45WVzFMc9XUmwEI5D1ndaW35wLEXquTBcKEA="
  [mod."github.com/willabides/kongplete"]
    version = "v0.2.0"
    hash = "sha256-KSk/sinPVj6AlXDI6WPktA78kUfli0+6qu9M6PZh3Qg="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.53.0"
    hash = "sha256-B7LSUQARnc4mpFjHj4jvJJh/rBAHGtKm1p+qFib+Pqk="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.28.0"
    hash = "sha256-bilBBr2cuADs9bQ7swnGLTuC7h0DooU6BQtrQqMqIjs="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"]
    version = "v1.28.0"
    hash = "sha256-nst5au6viPt71JG2TOd6JKfJGJ3QfbktC321XQJUfbU="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.28.0"
    hash = "sha256-k3p1lYcvrODwIkZo/j2jvCoDFUelz4yVJEEVdUKUmGU="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.28.0"
    hash = "sha256-X48fV4A9vgxfjBpmUIQumod2nyI+tUc5lnhFkeKBRsc="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.28.0"
    hash = "sha256-8uxmlm0/5VGoWegxwy0q8NgeY+pyicSoV08RkvD9Q98="
  [mod."golang.org/x/crypto"]
    version = "v0.27.0"
    hash = "sha256-8HP4+gr4DbXI22GhdgZmCWr1ijtI9HNLsTcE0kltY9o="
  [mod."golang.org/x/net"]
    version = "v0.29.0"
    hash = "sha256-dH9Rdf5T04KJ4B5WvIZh12ogMbADWiWgIt77nvPTk2k="
  [mod."golang.org/x/sys"]
    version = "v0.25.0"
    hash = "sha256-PXZ9EQZ7SFpcL7d3E1+KGTxziYlHEIZPfoXEbnaVD3I="
  [mod."golang.org/x/term"]
    version = "v0.24.0"
    hash = "sha256-PfC5psjzEWKRm1DlnBXX0ntw9OskJFrq1RRjyBa1lOk="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20240701130421-f6361c86f094"
    hash = "sha256-uDvld45ensSUweUJYFdUfVt/0mNRrexpuQ3Jas3GMv4="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240701130421-f6361c86f094"
    hash = "sha256-ass/74EkCljwk7DaASDtK2zipn2cZv6tCLKvwONUWgY="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."gotest.tools/v3"]
    version = "v3.5.1"
    hash = "sha256-ps2GEc3P2xvlrU4TCtXz+nLTxyP0RrF7SScz5jUqE5E="
