name: Govulncheck
on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/**'
      - '**.go'
      - go.mod
      - go.sum

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: govulncheck
      uses: golang/govulncheck-action@v1
      with:
        go-version-input: '${{ vars.GO_VERSION }}'
        go-package: ./...
