name: Tests
on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
    paths:
      - '.github/**'
      - 'cmd/**'
      - 'internal/**'
      - 'sso/**'
      - go.mod
      - go.sum

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Tests
      run: make .build-tests
    
    - name: Upload to codecov
      uses: codecov/codecov-action@v3
